sudo: false
language: node_js

install:
  - yarn install --no-progress --frozen-lockfile

script:
  - yarn test

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "12"
    - os: linux
      node_js: "10"
    - os: linux
      node_js: "8"

cache:
  yarn: true
